name: npm
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build application 5
        run: |
          echo "AWS_SECRET_ACCESS_KEY=tMWgQXmAm1AsOpf396erDeV6LmY0i8Oz1+EA17sW"
